app/views/main.py
# 导入类库
from flask import request,Blueprint, render_template, current_app, flash, redirect, url_for
from itsdangerous import TimedJSONWebSignatureSerializer as Serializer
from werkzeug.security import generate_password_hash, check_password_hash
from app.forms import PostsForm
from app.models import Posts,User
from app.extensions import db
from flask_login import current_user,login_required


# 创建蓝本
main = Blueprint('main', __name__)


# 添加视图函数
@main.route('/', methods=['GET', 'POST'])
def index():
    uip=None
    form = PostsForm()
    if form.validate_on_submit():
        if not current_user.is_authenticated:
            flash('登录后才可发表')
            return redirect(url_for('user.login'))
        u = current_user._get_current_object()
        p = Posts(content=form.content.data, user=u)
        db.session.add(p)
        flash('发表成功')
        return redirect(url_for('main.index'))
    if request.args.get('uip'):
        # 展示查看的博客作者的所有博客
        uip = request.args.get('uip')
        page = request.args.get('page', 1, int)
        u = User.query.filter(User.id == uip).first()
        pagination = u.posts.filter(Posts.rid == 0).paginate(page=page, per_page=2, error_out=False)
        posts = pagination.items
    else:
        # 读取所有的发表博客数据
        page = request.args.get('page',1,int)
        pagination = Posts.query.filter(Posts.rid == 0).order_by(Posts.timestamp.desc()).paginate(page=page, per_page=1, error_out=False)
        posts = pagination.items
    return render_template('main/index.html', form=form, posts=posts,pagination=pagination,uip=uip)


"""
# 展示查看的博客作者的所有博客
@main.route('/show/')
def show_blog():
    form = PostsForm()
    if form.validate_on_submit():
        if not current_user.is_authenticated:
            flash('登录后才可发表')
            return redirect(url_for('user.login'))
        u = current_user._get_current_object()
        p = Posts(content=form.content.data, user=u)
        db.session.add(p)
        flash('发表成功')
        return redirect(url_for('main.index'))
    uip = request.args.get('uip')

    page = request.args.get('page',1,int)
    u = User.query.filter(User.id == uip).first()
    pagination = u.posts.paginate(page=page, per_page=2, error_out=False)
    posts = pagination.items
    return render_template('main/index.html', form=form, posts=posts,pagination=pagination,uip=uip)
"""


# 查看某一篇博客的详细信息
@main.route('/ss_ss/',methods=['GET', 'POST'])
def ss_show():
    pip = request.args.get('pip')
    posts_user = Posts.query.get(pip)


    form = PostsForm()
    if form.validate_on_submit():
        if not current_user.is_authenticated:
            flash('登录后才可发表')
            return redirect(url_for('user.login'))
        u = current_user._get_current_object()
        p = Posts(content=form.content.data, user=u,rid=pip)

        db.session.add(p)
        flash('发表成功')
        return redirect(url_for('main.ss_show',pip=pip))

    page = request.args.get('page', 1, int)
    pagination = Posts.query.filter(Posts.rid == pip,).order_by(Posts.timestamp.desc()).paginate(page=page, per_page=1,error_out=False)
    posts = pagination.items
    return render_template('main/test.html', form=form, posts=posts, pagination=pagination, posts_user=posts_user,pip=pip)

# 我发表的
@main.route('/usershow/')
@login_required
def myposts():

    form = PostsForm()
    if form.validate_on_submit():
        if not current_user.is_authenticated:
            flash('登录后才可发表')
            return redirect(url_for('user.login'))
        u = current_user._get_current_object()
        p = Posts(content=form.content.data, user=u)

        db.session.add(p)
        flash('发表成功')
        return redirect(url_for('main.ss_show'))
    page = request.args.get('page', 1, int)
    MY = request.args.get('MY')
    if MY:
        pagination = Posts.query.filter(Posts.uid == current_user.id,Posts.rid == 0).order_by(Posts.timestamp.desc()).paginate(page=page, per_page=1, error_out=False)

    else:
        pagination = Posts.query.filter(Posts.uid == current_user.id,Posts.rid != 0).order_by(Posts.timestamp.desc()).paginate(page=page, per_page=1, error_out=False)
    posts = pagination.items
    return render_template('main/myposts.html', form=form, posts=posts, pagination=pagination,MY=MY)


# 我收藏的
@main.route('/collectposts/')
@login_required
def collectposts():
    form = PostsForm()
    if form.validate_on_submit():
        if not current_user.is_authenticated:
            flash('登录后才可发表')
            return redirect(url_for('user.login'))
        u = current_user._get_current_object()
        p = Posts(content=form.content.data, user=u)

        db.session.add(p)
        flash('发表成功')
        return redirect(url_for('main.ss_show'))
    page = request.args.get('page',1)
    pagination = current_user.favorites.order_by(Posts.timestamp.desc()).paginate(page=page, per_page=1, error_out=False)
    posts = pagination.items
    return render_template('main/collectposts.html', form=form, posts=posts, pagination=pagination)


"""

# 生成token
@main.route('/generate/')
def generate():
    s = Serializer(current_app.config['SECRET_KEY'], expires_in=3600)
    token = s.dumps({'id': 250})
    return token


# 校验token
@main.route('/check/<token>')
def check(token):
    s = Serializer(current_app.config['SECRET_KEY'])
    data = s.loads(token)
    return str(data['id'])


@main.route('/jiami/')
def jiami():
    return generate_password_hash('123456')




"""

app/views/user.py
from flask import Blueprint, render_template, flash, redirect, url_for, current_app, request
from app.forms import RegisterForm, LoginForm, UploadForm
from app.email import send_mail
from app.models import User
from app.extensions import db, photos
from itsdangerous import TimedJSONWebSignatureSerializer as Serializer, SignatureExpired, BadSignature
from flask_login import login_user, logout_user, login_required, current_user
import os
from PIL import Image


user = Blueprint('user', __name__)


# 用户注册
@user.route('/register/', methods=['GET', 'POST'])
def register():
    form = RegisterForm()
    if form.validate_on_submit():
        # 需要根据表单数据创建用户模型对象
        u = User(username=form.username.data,
                 password=form.password.data,
                 email=form.email.data)
        # 保存到数据库中
        db.session.add(u)
        # 手动提交
        db.session.commit()
        # 准备token
        s = Serializer(current_app.config['SECRET_KEY'], expires_in=3600)
        token = s.dumps({'id': u.id})
        # 发送用户激活邮件
        send_mail('账户激活',
                  form.email.data,
                  'email/activate.html',
                  username=form.username.data,
                  token=token)
        # 弹出消息提示用户下一步操作
        flash('注册成功，请点击邮件中的链接完成激活')
        return redirect(url_for('main.index'))
    return render_template('user/register.html', form=form)


# 用户账户激活
@user.route('/activate/<token>')
def activate(token):
    s = Serializer(current_app.config['SECRET_KEY'])
    try:
        data = s.loads(token)
    except SignatureExpired as e:
        flash('token已过期，激活失败')
        return redirect(url_for('main.index'))
    except BadSignature as e:
        flash('token有误，激活失败')
        return redirect(url_for('main.index'))

    # 根据token中携带的用户信息，在数据库中查询用户
    u = User.query.get(data['id'])
    if data.get('email',False):
        u.email = data['email']
        db.session.add(u)
    # 判断是否激活
    if not u.confirmed:
        # 没有激活才需要激活
        u.confirmed = True
        # 再次保存修改
        db.session.add(u)
    flash('激活成功')
    return redirect(url_for('user.login'))


# 用户登录
@user.route('/login/', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        u = User.query.filter(User.username == form.username.data).first()
        if not u:
            flash('无效的用户名')
        elif not u.confirmed:
            flash('账户尚未激活，请激活后再登录')
        elif not u.verify_password(form.password.data):
            flash('无效的密码')
        else:
            flash('登录成功')
            # 用户登录，可以完成记住我的功能，还可以设置记住的时间
            login_user(u, remember=form.remember.data)
            return redirect(request.args.get('next') or url_for('main.index'))
    return render_template('user/login.html', form=form)


# 用户退出
@user.route('/logout/')
def logout():
    flash('您已退出登录')
    logout_user()
    return redirect(url_for('main.index'))


@user.route('/profile/')
# 保护路由，该路由必须登录才能访问
@login_required
def profile():
    return render_template('user/profile.html')


@user.route('/icon/', methods=['GET', 'POST'])
def icon():
    form = UploadForm()
    if form.validate_on_submit():
        # 提取上传文件信息
        photo = form.photo.data
        # 提取文件后缀
        suffix = os.path.splitext(photo.filename)[1]
        # 生成随机文件名
        filename = random_string() + suffix
        # 保存上传文件
        photos.save(photo, name=filename)
        # 拼接文件路径名
        pathname = os.path.join(current_app.config['UPLOADED_PHOTOS_DEST'], filename)
        # 打开文件
        img = Image.open(pathname)
        # 设置尺寸
        img.thumbnail((64, 64))
        # 重新保存
        img.save(pathname)
        # 删除原来的头像文件（默认头像除外）
        if current_user.icon != 'default.jpg':
            os.remove(os.path.join(current_app.config['UPLOADED_PHOTOS_DEST'], current_user.icon))
        # 保存头像
        current_user.icon = filename
        db.session.add(current_user)
        flash('头像修改成功')
    img_url = url_for('static', filename='upload/'+current_user.icon)
    return render_template('user/icon.html', form=form, img_url=img_url)


def random_string(length=32):
    from random import choice
    base_str = 'abcdefghijklmnopqrstuvwxyz1234567890'
    return ''.join(choice(base_str) for i in range(length))

from app.forms import ChangePasswordForm
# 修改密码
@user.route('/changepassword/',methods=['GET','POST'])
@login_required
def changepassword():
    form = ChangePasswordForm()
    if form.validate_on_submit():
        if current_user.verify_password(form.old_password.data):
            current_user.password=form.password.data
            db.session.add(current_user)
            flash('修改成功，烦请重新登陆')
            logout_user()
            return redirect(url_for('.login'))

        else:
            flash('原始密码错误，修改失败，请重新修改，')
    return render_template('user/changepwd.html',form=form)

from app.forms import ChangeEmailForm
@user.route('/changeemail/',methods=['GET','POST'])
@login_required
def changeemail():
    form = ChangeEmailForm()
    if form.validate_on_submit():
        s = Serializer(current_app.config['SECRET_KEY'],expires_in=360)
        token = s.dumps({'id':current_user.id,'email':form.email.data})
        send_mail(
            '修改邮箱',
            form.email.data,
            'email/activate.html',
            username=current_user.username,
            token = token
        )
        flash('已发送验证邮件，请点击邮件中的连接进行修改')
        return redirect(url_for('main.index'))
    return render_template('user/changeemail.html', form=form)



"""

#修改密码
@user.route('/changepassword/',methods=['GET','POST'])
def changepassword():
    form=ChangePasswordForm()
    if form.validate_on_submit():

        if not current_user.verify_password(form.old_password.data):
            flash('原密码输入错误')
        else:
            current_user.password=form.password.data
            db.session.add(current_user)
            flash('密码更改成功')
            return redirect(url_for('user.login'))
    return render_template('user/changepassword.html',form=form)


#修改邮箱
@user.route('/changeemail/',methods=["GET","POST"])
def changeemail():
    form=ChangeEmailForm()
    if form.validate_on_submit():
        email=form.email.data
        s = Serializer(current_app.config['SECRET_KEY'], expires_in=3600)
        token = s.dumps({'id': current_user.id,'email':email})
        send_mail('账户激活',
                  form.email.data,
                  'email/activate.html',
                  username=current_user.username,
                  token=token)

        flash('修改成功，请点击邮件中的链接完成激活')
        return redirect(url_for('main.index'))
    return render_template('user/changeemail.html', form=form)

"""

app/templates/common/base.html
{# 继承自bootstrap基础模板 #}
{% extends 'bootstrap/base.html' %}

{# 导入快速渲染表单的宏 #}
{% from 'bootstrap/wtf.html' import quick_form %}

{# 定制标题 #}
{% block title %}博客中心{% endblock %}

{# 定制内容 #}
{% block content %}
    <div class="container">
        {% for message in get_flashed_messages() %}
            <div class="alert alert-warning alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span>
                </button>
                {{ message }}
            </div>
        {% endfor %}
        {% block page_content %}默认内容{% endblock %}
    </div>
{% endblock %}

{# 定制导航条 #}
{% block navbar %}
    <nav class="navbar navbar-inverse" style="border-radius: 0px;">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                        data-target=".navbar-collapse" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{{ url_for('main.index') }}">首页</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li><a href="{{ url_for('main.myposts',MY=1) }}">我发表的</a></li>
                    <li><a href="{{ url_for('main.myposts') }}">我回复的</a></li>
                    <li><a href="{{ url_for('main.collectposts') }}">收藏的</a></li>

                </ul>
                <ul class="nav navbar-nav navbar-right">
                {% if current_user.is_authenticated %}
                    <li><a href="{{ url_for('user.logout') }}">退出</a></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                           aria-expanded="false">{{ current_user.username }} <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="{{ url_for('user.profile') }}">详情信息</a></li>
                            <li><a href="{{ url_for('user.changepassword') }}">修改密码</a></li>
                            <li><a href="{{ url_for('user.changeemail') }}">修改邮箱</a></li>

                            <li><a href="{{ url_for('user.icon') }}">修改头像</a></li>
                        </ul>
                    </li>
                {% else %}
                    <li><a href="{{ url_for('user.login') }}">登录</a></li>
                    <li><a href="{{ url_for('user.register') }}">注册</a></li>
                {% endif %}
                </ul>
            </div><!-- /.navbar-collapse -->
        </div><!-- /.container -->
    </nav>
{% endblock %}

{% block scripts %}
    {{ super() }}
    {{ moment.include_moment() }}
    {{ moment.locale('zh-CN') }}
{% endblock %}

app/templates/common/macro.html
{% macro show_pagiantion(pagiantion,endpoint) %}

    <nav aria-label="Page navigation">
        <ul class="pagination">
            {# 上一页 #}
            <li {% if not pagiantion.has_prev %}class="disabled"{% endif %}>
                <a href="{% if pagiantion.has_prev %}{{ url_for(endpoint,page=pagiantion.prev_num,**kwargs) }}{% else %}#{% endif %}" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>

            {# 中间页码 #}
            {% for p in pagiantion.iter_pages() %}
                {% if p %}
                    <li {% if pagiantion.page==p %} class="active" {% endif %}><a href="{{ url_for(endpoint,page=p,**kwargs) }}">{{ p }}</a></li>
                {% else %}
                    <li><a href="#">&hellip;</a></li>
                {% endif %}

            {% endfor %}


            {# 下一页 #}
            <li {% if not pagiantion.has_next %}class="disabled"{% endif %}>
                <a href="{% if pagiantion.has_next %}{{ url_for(endpoint,page=pagiantion.next_num,**kwargs) }}{% else %}#{% endif %}" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
        </ul>
    </nav>

{% endmacro %}